%YAML 1.2
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: python
    common_args: &common
      api_key: foo

  tasks:
    - ansible.builtin.debug:
        var: ansible_python_interpreter

    - name: check for non-existent key
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k1
        state: exists
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists != false

    - name: check default key creation
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k2
        state: present
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists == false or result.key.algorithm != "hmac-md5"

    - name: check key removal
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k2
        state: absent
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.changed != true

    - name: check non-default key creation
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k3
        state: present
        algorithm: hmac-sha256
        key: +8fQxgYhf5PVGPKclKnk8ReujIfWXOw/aEzzPPhDi6AGagpg/r954FPZdzgFfUjnmjMSA1Yu7vo6DQHVoGnRkw==
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists == false or result.key.algorithm != "hmac-sha256" or result.key.key
        != "+8fQxgYhf5PVGPKclKnk8ReujIfWXOw/aEzzPPhDi6AGagpg/r954FPZdzgFfUjnmjMSA1Yu7vo6DQHVoGnRkw=="

    - name: check key existence
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k3
        state: exists
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists == false or result.key.algorithm != "hmac-sha256" or result.key.key
        != "+8fQxgYhf5PVGPKclKnk8ReujIfWXOw/aEzzPPhDi6AGagpg/r954FPZdzgFfUjnmjMSA1Yu7vo6DQHVoGnRkw=="

    - name: check key algorithm change
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k3
        state: present
        algorithm: hmac-sha512
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists == false or result.key.algorithm != "hmac-sha512"

    - name: check key removal
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: k3
        state: absent
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.changed != true

    - name: leave key for zone tests
      kpfleming.powerdns_auth.tsigkey:
        <<: *common
        name: axfr-key
        state: present
      ignore_errors: true
      register: result

    - name: display result
      ansible.builtin.debug:
        var: result

    - name: check result
      ansible.builtin.debug:
        msg: success
      failed_when: result['exception'] is defined or result.failed == true or result.key.exists == false or  result.key.algorithm != "hmac-md5"
