on:
  push:
    paths:
    - 'pdns_auth_zone.py'
    - 'api-swagger.json'
    - 'tests/*'
    - '.github/workflow/*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/kpfleming/apaz-test-images:pdns4.3-python3
    steps:
    - uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: stop pdns_server
      run: kill $(cat /run/pdns.pid)
