on:
  push:
    paths:
    - 'pdns_auth_zone.py'
    - 'api-swagger.json'

jobs:
  test:
    runs-on: ubuntu-latest
    container: kpfleming/apaz-test-images:pdns4.3-python3
    steps:
    - uses: actions/checkout@v2
