name: CI

on:
  push:
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_*_image.sh'
    - 'workflow-support/start_server.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_*_image.sh'
    - 'workflow-support/start_server.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  schedule:
    - cron: "35 4 * * 6"

env:
  registry_base: 'quay.io/apaa-test-images'

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      # workaround to make registry_base available in jobs
      registry_base: ${{ env.registry_base }}
    steps:
    - uses: actions/checkout@v2
    - id: preflight
      uses: ./.github/actions/ci-preflight
  image-tox:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/make-tox-image
      if: needs.preflight.outputs.need_image == 'true'
      with:
        image_name: ${{ needs.preflight.outputs.registry_base }}/tox:${{ needs.preflight.outputs.image_tag }}
        quay_username: ${{ secrets.QUAY_BOT_NAME }}
        quay_password: ${{ secrets.QUAY_BOT_PASSWORD }}
  image-pdns:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    - image-tox
    strategy:
      matrix:
        pdns: [4.3, 4.4, 4.5, 4.6, master]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/make-pdns-image
      if: needs.preflight.outputs.need_image == 'true'
      with:
        pdns_version: ${{ matrix.pdns }}
        base_image: ${{ needs.preflight.outputs.registry_base }}/tox:${{ needs.preflight.outputs.image_tag }}
        image_name: ${{ needs.preflight.outputs.registry_base }}/pdns-${{ matrix.pdns }}:${{ needs.preflight.outputs.image_tag }}
        quay_username: ${{ secrets.QUAY_BOT_NAME }}
        quay_password: ${{ secrets.QUAY_BOT_PASSWORD }}
  test:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    - image-pdns
    strategy:
      matrix:
        pdns: [4.3, 4.4, 4.5, 4.6, master]
        python: [py38, py39, py310]
      fail-fast: false
    container:
      image: docker://${{ needs.preflight.outputs.registry_base }}/pdns-${{ matrix.pdns }}:${{ needs.preflight.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v2
    - name: start pdns_server
      run: workflow-support/start_server.sh
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
      env:
        pdns_version: ${{ matrix.pdns }}
