name: CI

on:
  push:
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/start_server.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/start_server.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  schedule:
    - cron: "35 4 * * 6"

env:
  image_base: 'quay.io/km6g-ci-images/ansible-powerdns-auth'

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      # workaround to make image_base available in jobs
      image_base: ${{ env.image_base }}
    steps:
    - uses: actions/checkout@v3
    - id: preflight
      uses: ./.github/actions/ci-preflight
  ci-image:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    strategy:
      matrix:
        pdns: [4.4, 4.5, 4.6, master]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/make-ci-image
      if: needs.preflight.outputs.need_image == 'true'
      with:
        pdns_version: ${{ matrix.pdns }}
        image_name: ${{ needs.preflight.outputs.image_base }}:pdns-${{ matrix.pdns }}-${{ needs.preflight.outputs.image_tag }}
        quay_username: ${{ secrets.QUAY_BOT_NAME }}
        quay_password: ${{ secrets.QUAY_BOT_PASSWORD }}
  test:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    - ci-image
    strategy:
      matrix:
        pdns: [4.4, 4.5, 4.6, master]
        python: [py38, py39, py310, py311]
      fail-fast: false
    container:
      image: ${{ needs.preflight.outputs.image_base }}:pdns-${{ matrix.pdns }}-${{ needs.preflight.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: start pdns_server
      run: workflow-support/start_server.sh
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
      env:
        pdns_version: ${{ matrix.pdns }}
