name: CI

on:
  push:
    branches:
    - main
    paths:
    - '*.py'
    - 'api-swagger.json'
    - 'tests/test-*.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.image_files }}
    steps:
    - id: skip_check
      uses: dorny/paths-filter@v2
      with:
        base: main
        filters: |
          image_files:
          - 'tox.ini'
          - 'tests/make_*_container.sh'
          - '.github/workflows/build-image-and-ci-pr.yml'
  test:
    runs-on: ubuntu-20.04
    needs: preflight
    if: ${{ needs.preflight.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        pdns: [4.2, 4.3, master]
        python: [py36, py37, py38, py39]
      fail-fast: false
    container:
      image: docker://quay.io/apaa-test-images/pdns-${{ matrix.pdns }}:main
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
    env:
      pdns_version: ${{ matrix.pdns }}
