name: CI

on:
  push:
    branches:
    - master
    - 'branch-[1-9]+.[0-9]+'
    tags:
    - 'v[1-9]+.[0-9]+.[0-9]+'
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/playbook.yml'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  repository_dispatch:
    types: [trigger-ci]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pdns: [4.2, 4.3, master]
    container:
      image: docker://quay.io/kpfleming/apaa-test-images:pdns-${{ matrix.pdns }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: run test playbook for pdns_auth_tsigkey
      run: /ansible/bin/ansible-playbook -M . -i localhost, tests/test-patk-playbook.yml
    - name: run test playbook for pdns_auth_zone
      run: /ansible/bin/ansible-playbook -M . -i localhost, tests/test-paz-playbook.yml
