name: Cleanup PR Images

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  image_details:
    runs-on: ubuntu-20.04
    outputs:
      image_registry: ${{ steps.details.outputs.image_registry }}
      registry_account: ${{ steps.details.outputs.registry_account }}
      repo_name: ${{ steps.details.outputs.repo_name }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
  clean-image:
    runs-on: ubuntu-20.04
    needs:
    - image_details
    strategy:
      matrix:
        pdns: [4.4, 4.5, 4.6, master]
    steps:
    - uses: kpfleming/composite-actions/clean-pr-image@main
      with:
        image_registry: ${{ needs.image_details.outputs.image_registry }}
        registry_account: ${{ needs.image_details.outputs.registry_account }}
        registry_token: ${{ secrets.QUAY_API_TOKEN }}
        repo_name: ${{ needs.image_details.outputs.repo_name }}
        tag_prefix: pdns-${{ matrix.pdns }}-
