name: Lint checks

on:
  pull_request:
    branches:
    - main
    paths:
    - 'tox.ini'
    - 'pdns_auth_tsigkey.py'
    - 'pdns_auth_zone.py'
    - 'workflow-support/*.sh'
    - '.github/workflows/lint.yml'
    - '.github/actions/lint/action.yml'

jobs:
  image_details:
    runs-on: ubuntu-20.04
    outputs:
      image_base: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/${{ steps.details.outputs.repo_name }}
    steps:
    - uses: actions/checkout@v3
    - id: details
      uses: ./.github/actions/image-details
  lint:
    runs-on: ubuntu-20.04
    needs:
    - image_details
    container:
      image: ${{ needs.image_details.outputs.image_base }}:pdns-master-main
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/lint
      with:
        lintly_token: ${{ secrets.LINTLY_TOKEN }}
