name: Lint checks

on:
  pull_request:
    branches:
    - main
    paths:
    - 'tox.ini'
    - 'pdns_auth_tsigkey.py'
    - 'pdns_auth_zone.py'
    - '.github/workflows/lint.yml'
    - '.github/actions/lint/action.yml'

jobs:
  lint:
    runs-on: ubuntu-20.04
    container:
      image: docker://quay.io/apaa-test-images/pdns-master:main
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/lint
      with:
        lintly_token: ${{ secrets.LINTLY_TOKEN }}
