name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  image_details:
    runs-on: ubuntu-20.04
    outputs:
      image_base: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/${{ steps.details.outputs.repo_name }}
    steps:
    - uses: actions/checkout@v3
    - id: details
      uses: ./.github/actions/image-details
  publish:
    runs-on: ubuntu-20.04
    needs:
    - image_details
    container:
      image: ${{ needs.image_details.outputs.image_base }}:pdns-master-main
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/publish
      with:
        galaxy_token: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        tag: ${{ github.ref_name }}
