name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    container:
      image: docker://quay.io/apaa-test-images/tox:main
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/publish
      with:
        galaxy_token: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        tag: ${{ github.ref_name }}
