name: "Image Details"
outputs:
  image_registry:
    value: quay.io
  registry_account:
    value: km6g-ci-images
  repo_name:
    value: ${{ steps.repo_name.outputs.name }}
runs:
  using: "composite"
  steps:
  - id: repo_name
    run: echo "::set-output name=name::${GITHUB_REPOSITORY##*/}"
    shell: bash
